### ISSUE TITLE
missing variables in demo.py

### ISSUE THREAD

**Issue by svamsip** [jxbbb/ADAPT#1]
here, what do `caps` and `infos` refer to 

https://github.com/jxbbb/ADAPT/blob/66353c27865088c146cd314639fc40f4afcaba0c/demo.py#L130-L135

+ It would be great if you can provide the Dockerfile.

**Comment by jxbbb** [comment]
Thank you for your interest. Well actually the `demo.py` file was first created to visualize the raw videos and is no longer used now. If you want to run a quick demo, please run `scripts/inference.sh`. We will delete the demo.py soon, and release another visualization code.

And for docker image you can just run `sh launch_container.sh` to get up.

**Comment by svamsip** [comment]
Thanks for updating documentation for model files!

I was able to execute inference using the container.
