### ISSUE TITLE
[Installation as Conda] Mismatch between python version and pandas version

### ISSUE THREAD

**Issue by MoMo569377793** [jxbbb/ADAPT#20]
I created a python 3.8 environment called ADAPT based on Getting Started, but encountered an error when installing pandas
The original requirements file asked for pandas version == 2.1.3
![image](https://github.com/jxbbb/ADAPT/assets/83206978/547fff81-672c-4980-a764-8afee07cc68b)
However, version 2.1.3 must correspond to python 3.9.
![image](https://github.com/jxbbb/ADAPT/assets/83206978/dac25d8f-481e-45ae-909d-a9b5061d795d)
Did I make a mistake somewhere?
What should I do, upgrade python to 3.9 or downgrade pandas to 2.0.3?

**Comment by MoMo569377793** [comment]
I installed version 2.0.3 of pandas and ADAPT now works!

**Comment by YandL6** [comment]
Hello, I encountered the same error. In addition to that, I also have another error: when installing deepspeed==0.14.0, I received an error as well. Therefore, I tried installing deepspeed==0.16.5, but I encountered an error again. Have you experienced this issue?
![Image](https://github.com/user-attachments/assets/9dc5176d-79d4-49a6-a7ad-95c1b18e25f7)
