### ISSUE TITLE
Request Dataset Authorization

### ISSUE THREAD

**Issue by pixeli99** [jxbbb/ADAPT#6]
I am very interested in your work, can you provide raw video data?

I have sent you an email but have not received a reply yet, looking forward to your reply！

Thank you!

**Comment by chefbaker4** [comment]
I find the raw data available for download here: http://bdd-data.berkeley.edu/download.html

**Comment by pixeli99** [comment]
> I find the raw data available for download here: http://bdd-data.berkeley.edu/download.html

Thanks!
