### ISSUE TITLE
CARLA demo and results

### ISSUE THREAD

**Issue by TonyXuQAQ** [jxbbb/ADAPT#8]
Hi, nice work and quite inspiring! I noticed that you mentioned you have deployed your system in CARLA and real-world scenarios, so could you provide some demos or quantitive results? Or did I miss anything? I just wanna know the generalization performance of your system.

Thanks a lot for your sincere help.

**Comment by jxbbb** [comment]
You can see these in https://events.infovaya.com/presentation?id=93224

**Comment by TonyXuQAQ** [comment]
Thanks for the information! One more question, are these generalization experiments conducted in a zero-shot way, or fine-tune is required?

**Comment by jxbbb** [comment]
Yes, they are all zero-shot except for those on the original dataset. And we will release other demos conducted on datasets like nuscenes or waymo, also in a zero-shot manner.

**Comment by TonyXuQAQ** [comment]
Thanks for the information! I'm closing this issue.

**Comment by yixiao1** [comment]
> You can see these in https://events.infovaya.com/presentation?id=93224

Hi, very nice work! 
In the link you provided I did not find the demo and quantitative results of CARLA and the real-world experiments. Could you please provide more information about this? Many thanks!
